services:

  server:
    image: my-app-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/mydb?sslmode=disable
    container_name: my-app-backend-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: my-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresDB:/var/lib/postgresql/data

volumes:
  postgresDB: